CREATE TABLE PRICES (
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE FLOAT,
    CURR VARCHAR(3),
    PRIMARY KEY (BRAND_ID, PRODUCT_ID, PRICE_LIST)
);
